maxconn = 32
httpchk = "GET /"
options = "httpclose"
deployment = false

[front-end]
listen = "*"
port = 80
mode = "http"

[status]
enabled = false
listen = "*"
port = 9000
user = "admin"
password = "password"
uri = "/haproxy-stats"
